
services:
  postgres:
    image: postgres:latest
    container_name: organizations-db
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ../.env

volumes:
  postgres_data: